// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod embedding {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum EmbeddingFeatureDataFlatOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct EmbeddingFeatureDataFlat<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for EmbeddingFeatureDataFlat<'a> {
  type Inner = EmbeddingFeatureDataFlat<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> EmbeddingFeatureDataFlat<'a> {
  pub const VT_FLOAT32_VECTOR: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    EmbeddingFeatureDataFlat { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args EmbeddingFeatureDataFlatArgs<'args>
  ) -> flatbuffers::WIPOffset<EmbeddingFeatureDataFlat<'bldr>> {
    let mut builder = EmbeddingFeatureDataFlatBuilder::new(_fbb);
    if let Some(x) = args.float32_vector { builder.add_float32_vector(x); }
    builder.finish()
  }


  #[inline]
  pub fn float32_vector(&self) -> Option<flatbuffers::Vector<'a, f32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f32>>>(EmbeddingFeatureDataFlat::VT_FLOAT32_VECTOR, None)}
  }
}

impl flatbuffers::Verifiable for EmbeddingFeatureDataFlat<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f32>>>("float32_vector", Self::VT_FLOAT32_VECTOR, false)?
     .finish();
    Ok(())
  }
}
pub struct EmbeddingFeatureDataFlatArgs<'a> {
    pub float32_vector: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f32>>>,
}
impl<'a> Default for EmbeddingFeatureDataFlatArgs<'a> {
  #[inline]
  fn default() -> Self {
    EmbeddingFeatureDataFlatArgs {
      float32_vector: None,
    }
  }
}

pub struct EmbeddingFeatureDataFlatBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> EmbeddingFeatureDataFlatBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_float32_vector(&mut self, float32_vector: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(EmbeddingFeatureDataFlat::VT_FLOAT32_VECTOR, float32_vector);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> EmbeddingFeatureDataFlatBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    EmbeddingFeatureDataFlatBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<EmbeddingFeatureDataFlat<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for EmbeddingFeatureDataFlat<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("EmbeddingFeatureDataFlat");
      ds.field("float32_vector", &self.float32_vector());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `EmbeddingFeatureDataFlat`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_embedding_feature_data_flat_unchecked`.
pub fn root_as_embedding_feature_data_flat(buf: &[u8]) -> Result<EmbeddingFeatureDataFlat, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<EmbeddingFeatureDataFlat>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `EmbeddingFeatureDataFlat` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_embedding_feature_data_flat_unchecked`.
pub fn size_prefixed_root_as_embedding_feature_data_flat(buf: &[u8]) -> Result<EmbeddingFeatureDataFlat, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<EmbeddingFeatureDataFlat>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `EmbeddingFeatureDataFlat` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_embedding_feature_data_flat_unchecked`.
pub fn root_as_embedding_feature_data_flat_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<EmbeddingFeatureDataFlat<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<EmbeddingFeatureDataFlat<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `EmbeddingFeatureDataFlat` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_embedding_feature_data_flat_unchecked`.
pub fn size_prefixed_root_as_embedding_feature_data_flat_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<EmbeddingFeatureDataFlat<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<EmbeddingFeatureDataFlat<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a EmbeddingFeatureDataFlat and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `EmbeddingFeatureDataFlat`.
pub unsafe fn root_as_embedding_feature_data_flat_unchecked(buf: &[u8]) -> EmbeddingFeatureDataFlat {
  flatbuffers::root_unchecked::<EmbeddingFeatureDataFlat>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed EmbeddingFeatureDataFlat and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `EmbeddingFeatureDataFlat`.
pub unsafe fn size_prefixed_root_as_embedding_feature_data_flat_unchecked(buf: &[u8]) -> EmbeddingFeatureDataFlat {
  flatbuffers::size_prefixed_root_unchecked::<EmbeddingFeatureDataFlat>(buf)
}
#[inline]
pub fn finish_embedding_feature_data_flat_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<EmbeddingFeatureDataFlat<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_embedding_feature_data_flat_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<EmbeddingFeatureDataFlat<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod embedding

